### DISCUSSION TITLE
No possibility to set custom background color

### DISCUSSION THREAD

**Discussion by MichalskiMaximilian** [ericgio/react-bootstrap-typeahead#864] [Q&A]
Unfortunatly it is not possible to change the Background of the multiple selctor. Even the solution with the input props which works for `multiple:{false}` has no effect. The color doesn't change. 

Is there a possibility to fix this or another way to set the BackgroundColor when the multiple property is set?

```tsx
<Typeahead 
    id="buildings" 
    multiple={true}
    inputProps={{
        style: {
            backgroundColor: 'red'
        }
    }}
    size={'sm'}
    paginationText={CodeStrings.LoadMoreResults}
    options={buildings.sort((a, b) => a.idNum.localeCompare(b.idNum))} 
    placeholder={CodeStrings.InvestigationOrder.ChooseBuildingLand}
    selected={selectedBuildings}
    onChange={(option: any) => handleBuildingChange(option)}
    labelKey={(option: any) => `${option.idNum} ( ${option.economicUnit} )`}
    emptyLabel={CodeStrings.NoResults}
/>
```

**Comment by ericgio** [comment]
@MichalskiMaximilian that's right, the approach you're describing won't work for the multi-select input because it's a composite component meant to emulate the appearance of an input. There are inline styles setting the color to `transparent`, which is why you don't see any effect. The easiest way to apply a custom background color is to target the CSS class:

```css
.rbt-input {
  background-color: red;
}
```

**Reply by MichalskiMaximilian** [reply]
@ericgio 
Thanks for the information but i need to handle this dynamically and i can not say that every multi input should be red i need this just for some multi inputs.

**Reply by ericgio** [reply]
I'm having trouble imagining a case where you'd need to apply the color dynamically, can you describe your use case? If you just need to apply different colors to a defined set of inputs, you could also apply your own CSS class name to scope the different styles:

```css
.red-typeahead .rbt-input {
  background-color: red;
}

.green-typeahead .rbt-input {
  background-color: green;
}

.blue-typeahead .rbt-input {
  background-color: blue;
}
```
