### ISSUE TITLE
validationState: Change the color of the border of the input field

### ISSUE THREAD

**Issue by lorenzosjb** [ericgio/react-bootstrap-typeahead#335]
Feature request

Please add behavior, like the validationState (FormGroup), so a danger or success, can change the color of the border of the input field.
Thanks.

**Comment by ericgio** [comment]
This is already supported in single-select mode for Bootstrap v3 + v4:

```jsx
// BS3
<FormGroup validationState="success">
  <Typeahead {...} />
</FormGroup>

// BS4
<Typeahead
  inputProps={{
    className: classnames({
      'is-invalid': invalidCondition,
      'is-valid': validCondition,
    }),
  }}
/>
```

For validation of the multi-select in BS3, the next release will contain additional CSS to make it work. In the meantime, you can add the following to your styles:

```css
.has-error .rbt-input-multi.focus {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
  border-color: #843534;
}

.has-warning .rbt-input-multi.focus {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
  border-color: #66512c;
}

.has-success .rbt-input-multi.focus {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
  border-color: #2b542c;
}
```

#333 is tracking BS4 support for multi-select validation states.
