### ISSUE TITLE
Hint is truncated

### ISSUE THREAD

**Issue by johnf** [ericgio/react-bootstrap-typeahead#404]
### Version
3.2.4

### Steps to reproduce

https://codepen.io/johnfjohnf/pen/LMeZbO

### Expected Behavior

The full hint should be displayed in the input field

### Actual Behavior

The input field is being truncated.

### Possible fix

Adding the following javascript solves the issue for me

``` css
.rbt-input-hint {
  width: 100%;                 
}
```
