### ISSUE TITLE
Make component render correctly when used with `input-group`

### ISSUE THREAD

**Issue by atuttle** [ericgio/react-bootstrap-typeahead#74]
Given:

``` html
<div className='form-group'>
    <label className='control-label col-md-3'>To</label>
    <div className='col-md-6'>
        <div className="input-group">
            <Typeahead
                onInputChange={this.setDesignation}
                options={designationList}
                defaultSelected={ [ this.props.designation ] }
            />
            <div className="input-group-btn">
                <a className='btn btn-primary btn-block' href='/giving'>Browse...</a>
            </div>
        </div>
    </div>
</div>
```

The result is that the dropdown for selecting a value hovers over the input (instead of below it):

![image](https://cloud.githubusercontent.com/assets/46990/18169760/9ab52284-7029-11e6-9ea0-4f9e627673c1.png)

This is problematic because in single-selection mode it is not immediately obvious that you need to backspace away your selection in order to see the list again, if that's what you're trying to do:

![image](https://cloud.githubusercontent.com/assets/46990/18169895/29846196-702a-11e6-812b-f6fcddd54a7e.png)

I think this problem would go away if #73 were implemented.

**Comment by ericgio** [comment]
Seems like a CSS bug, thanks for reporting.

**Comment by ericgio** [comment]
It looks like the form and input groups add floats, which breaks the typeahead's layout. Adding the `clearfix` classname to the typeahead fixes the issue, though currently there's no way to pass a classname to the parent component.

Also note that the multi-selection version of the component has unexpected behavior when used inside an input group because it's a `div` styled to look like an input, and some of the styles aren't correctly applied.

**Comment by ericgio** [comment]
Opened https://github.com/ericgio/react-bootstrap-typeahead/issues/75 to deal with the `className` issue. Once that's fixed it should at least temporarily solve your issue here.

**Comment by atuttle** [comment]
Went only temporarily? (I'm only using single-select mode)

**Comment by ericgio** [comment]
Sorry, "temporarily" might be the wrong word. It's a stopgap solution since it would allow you to pass the `clearfix` classname and fix your issue. However, the longer-term fix is to make the component behave correctly when used within an input-group without forcing the developer to do anything.

**Comment by atuttle** [comment]
Makes sense, thanks.

**Comment by krembo** [comment]
I had this issue too. Fixed it with adding the following CSS: 

```CSS
.input-group .bootstrap-typeahead.open {
    position: static !important;
}
```

See if it can help you.

**Comment by jasonswearingen** [comment]
fyi with the new bootstrap 4 beta, rendering inside a ```input-group``` is further messed up.   putting the Typeahead by itself (not in an input-group) was my workaround.

**Comment by ericgio** [comment]
Fixed for Bootstrap 3 in v1.2.0. Bootstrap 4 is still officially unsupported.

**Comment by albertpeiro** [comment]
+1 for fixing this for Bootstrap 4

**Comment by albertpeiro** [comment]
Hi I just fixed this myself with some SCSS
https://gist.github.com/albertpeiro/9ab44912ddb43cc7ad96fd145425aa65

**Comment by alleroux** [comment]
@albertpeiro This isn't working for me with the new Bootstrap 4.0.0 release version.  As a work around I put the form-control class on the typeahead itself and it worked fine.  I had to add another class to remove the border and padding though.

**Comment by albertpeiro** [comment]
@alleroux good to know! can you share your gist?

**Comment by ericgio** [comment]
For anyone using Bootstrap 4 and having trouble getting input-groups working with the typeahead, adding the following CSS should work:

```css
.input-group > .rbt {
  -webkit-box-flex: 1;
  -moz-box-flex: 1;
  -webkit-flex: 1;
  -ms-flex: 1;
  flex: 1;
}

.input-group > .rbt:not(:first-child) > .form-control {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}

.input-group > .rbt:not(:last-child) > .form-control {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```

I'm working on adding this and a few other things to the package so that the component works better with BS4 out of the box. Main issue being tracked at #131.
